### ISSUE TITLE
Please add armhf to your architecure

### ISSUE THREAD

**Issue by MikeMitterer** [lucidsoftware/apt-boto-s3#15] opened 2017-04-05 14:18 UTC
I installed it manually on Raspi3

```bash
#!/bin/sh
apt-get install python python-pip
pip install boto3
wget https://raw.githubusercontent.com/lucidsoftware/apt-boto-s3/master/s3.py
cp s3.py /usr/lib/apt/methods/s3
chmod 755 /usr/lib/apt/methods/s3
```
and it works like a charm - Thanks!

**Comment by pauldraper** [comment] 2018-03-07 06:34
Duplicate of #13

**Closed as completed by pauldraper** 2018-03-07 06:34 UTC
Labels: duplicate, enhancement
